plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

def keystorePassword = rootProject.file('signing/keystore-password.txt').text.trim()

android {
    namespace 'com.kcmps.app'
    compileSdk 34

    defaultConfig {
        applicationId 'com.kcmps.app'
        minSdk 24
        targetSdk 34
        versionCode 3
        versionName '1.1.0'
    }

    signingConfigs {
        release {
            storeFile rootProject.file('signing/kcmps-release.keystore')
            storePassword keystorePassword
            keyAlias 'kcmps'
            keyPassword keystorePassword
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.core:core-splashscreen:1.0.1'
    implementation 'androidx.activity:activity-ktx:1.9.0'
}
